---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-addon: fluentd-elasticsearch.addons.k8s.io
  name: fluentd-elasticsearch
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-elasticsearch
subjects:
- kind: ServiceAccount
  name: fluentd-elasticsearch
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-elasticsearch
    k8s-addon: fluentd-elasticsearch.addons.k8s.io
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-elasticsearch
  template:
    metadata:
      labels:
        k8s-app: fluentd-elasticsearch
      name: fluentd-elasticsearch
      namespace: kube-system
    spec:
      serviceAccountName: fluentd-elasticsearch
      containers:
      - image: onfido/fluentd-es-aws:latest
        imagePullPolicy: Always
        name: fluentd-elasticsearch
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: fluentd-elasticsearch
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fluentd-elasticsearch
              key: secret-key
        - name: AWS_ELASTICSEARCH_URL
          value: https://ES_DOMAIN.eu-west-1.es.amazonaws.com
        - name: AWS_REGION
          value: eu-west-1
        - name: LOGSTASH_PREFIX
          value: fluentd
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
